import { useEffect, useState, type FormEvent } from "react";
import { createFileRoute, useNavigate } from "@tanstack/react-router";
import { useServerFn } from "@tanstack/react-start";
import { CheckCircle2, LoaderCircle, UserPlus } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { acceptAdminInvite, getInviteDetails } from "@/lib/admin.functions";

export const Route = createFileRoute("/invite")({ validateSearch: (search: Record<string, unknown>) => ({ token: typeof search["token"] === "string" ? search["token"] : "" }), head: () => ({ meta: [{ title: "Aceitar convite — Núcleo" }, { name: "description", content: "Conclua seu cadastro seguro no Núcleo." }, { property: "og:title", content: "Aceitar convite — Núcleo" }, { property: "og:description", content: "Conclua seu cadastro seguro no Núcleo." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary" }] }), component: InvitePage });
function InvitePage() {
  const { token } = Route.useSearch(); const navigate = useNavigate(); const details = useServerFn(getInviteDetails); const accept = useServerFn(acceptAdminInvite);
  const [invite, setInvite] = useState<{ email: string; departamento: string } | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [done, setDone] = useState(false);
  useEffect(() => { if (!token) { setError("Link de convite inválido."); setLoading(false); return; } void details({ data: { token } }).then(async (result) => { setInvite(result); const { data: authData } = await supabase.auth.getUser(); const savedName = authData.user?.user_metadata["full_name"]; if (authData.user?.email === result.email && typeof savedName === "string" && savedName.trim().length >= 2) { await accept({ data: { token, nome: savedName.trim() } }); await navigate({ to: "/dashboard", replace: true }); } }).catch((reason) => setError(reason instanceof Error ? reason.message : "Convite inválido.")).finally(() => setLoading(false)); }, [accept, details, navigate, token]);
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!invite) return; setLoading(true); setError(""); const form = new FormData(event.currentTarget); const nome = String(form.get("nome") ?? "").trim(); const password = String(form.get("password") ?? ""); if (nome.length < 2 || password.length < 8) { setError("Informe seu nome e uma senha de pelo menos 8 caracteres."); setLoading(false); return; } const { data, error: signupError } = await supabase.auth.signUp({ email: invite.email, password, options: { emailRedirectTo: `${window.location.origin}/invite?token=${token}`, data: { full_name: nome } } }); if (signupError) { setError(signupError.message); setLoading(false); return; } if (!data.session) { setDone(true); setLoading(false); return; } await accept({ data: { token, nome } }); await navigate({ to: "/dashboard", replace: true }); };
  return <main className="auth-atmosphere grid min-h-screen place-items-center px-4 py-10"><section className="w-full max-w-md rounded-lg border border-border bg-card p-6 shadow-2xl sm:p-8">{loading && !invite ? <div className="grid min-h-48 place-items-center"><LoaderCircle className="animate-spin" /></div> : error && !invite ? <p role="alert" className="text-sm text-destructive">{error}</p> : done ? <div className="text-center"><CheckCircle2 className="mx-auto size-10 text-primary" /><h1 className="mt-5 text-2xl font-semibold">Confirme seu e-mail</h1><p className="mt-2 text-sm text-muted-foreground">Enviamos uma confirmação para concluir seu acesso.</p></div> : invite ? <><UserPlus className="size-10 text-primary" /><h1 className="mt-6 text-2xl font-semibold">Aceitar convite</h1><p className="mt-2 text-sm text-muted-foreground">{invite.email} · {invite.departamento}</p><form className="mt-7 grid gap-4" onSubmit={submit}><div className="grid gap-2"><Label htmlFor="nome">Nome completo</Label><Input id="nome" name="nome" required minLength={2} /></div><div className="grid gap-2"><Label htmlFor="password">Crie uma senha</Label><Input id="password" name="password" type="password" required minLength={8} autoComplete="new-password" /></div>{error && <p role="alert" className="text-sm text-destructive">{error}</p>}<Button size="lg" disabled={loading}>{loading ? <LoaderCircle className="animate-spin" /> : <UserPlus />}Criar acesso</Button></form></> : null}</section></main>;
}
