import { useState } from "react";
import { createFileRoute } from "@tanstack/react-router";
import { Check, X } from "lucide-react";
import { AppShell } from "@/components/hub/app-shell";
import { PaymentBanner } from "@/components/hub/payment-banner";
import { StripeCheckout } from "@/components/hub/stripe-checkout";
import { Button } from "@/components/ui/button";
type PriceId="credits_100_brl"|"credits_300_brl"|"credits_1000_brl";
const packs=[{id:"credits_100_brl" as const,credits:100,price:49,label:"Essencial"},{id:"credits_300_brl" as const,credits:300,price:129,label:"Produtivo"},{id:"credits_1000_brl" as const,credits:1000,price:349,label:"Estúdio"}];
export const Route=createFileRoute("/pricing")({head:()=>({meta:[{title:"Créditos — LovableHub"},{name:"description",content:"Escolha um pacote de créditos LovableHub."},{property:"og:title",content:"Créditos — LovableHub"},{property:"og:description",content:"Pacotes de créditos para extensões e commits."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary"}]}),component:Pricing});
function Pricing(){const[selected,setSelected]=useState<PriceId|null>(null);return <><PaymentBanner/><AppShell><div className="mx-auto max-w-5xl"><div className="mb-10 text-center"><p className="text-xs font-medium uppercase text-primary">Créditos</p><h1 className="mt-2 text-3xl font-semibold">Escolha seu ritmo de criação</h1><p className="mt-3 text-muted-foreground">Créditos não expiram e ficam disponíveis após a confirmação.</p></div>{selected?<div className="border border-border bg-card"><div className="flex items-center justify-between border-b border-border p-4"><span className="font-medium">Checkout seguro</span><Button variant="ghost" size="icon" aria-label="Fechar checkout" onClick={()=>setSelected(null)}><X/></Button></div><StripeCheckout priceId={selected}/></div>:<div className="grid gap-4 md:grid-cols-3">{packs.map((pack,index)=><article key={pack.id} className="flex flex-col border border-border bg-card p-6"><span className="text-sm text-muted-foreground">{pack.label}</span><h2 className="mt-5 text-4xl font-semibold">{pack.credits}</h2><p className="text-sm text-muted-foreground">créditos</p><div className="my-7 h-px bg-border"/><p className="text-2xl font-semibold">R${pack.price}</p><ul className="my-7 space-y-3 text-sm text-muted-foreground"><li className="flex gap-2"><Check className="size-4 text-primary"/>Instalações e commits</li><li className="flex gap-2"><Check className="size-4 text-primary"/>Saldo em tempo real</li></ul><Button variant={index===1?"default":"outline"} onClick={()=>setSelected(pack.id)}>Comprar créditos</Button></article>)}</div>}</div></AppShell></>}