import { createFileRoute } from "@tanstack/react-router";
import { Building2 } from "lucide-react";
import { AppShell } from "@/components/hub/app-shell";
import { PageError, PageLoading } from "@/components/admin/page-state";
import { PageHeading } from "@/components/admin/page-heading";
import { useAdminData } from "@/hooks/use-admin-data";
import { departments } from "@/lib/admin-types";
const descriptions = { ADMIN: "Administração e controle do sistema", FINANCEIRO: "Operações e rotinas financeiras", VENDAS: "Relacionamento e atividades comerciais", ESTOQUE: "Materiais, inventário e logística", JURIDICO: "Contratos e assuntos legais" } as const;
export const Route = createFileRoute("/_authenticated/departments")({ head: () => ({ meta: [{ title: "Departamentos — Núcleo" }, { name: "description", content: "Visão dos departamentos e seus integrantes." }, { property: "og:title", content: "Departamentos — Núcleo" }, { property: "og:description", content: "Visão dos departamentos e seus integrantes." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary" }] }), component: Departments });
function Departments() { const { data, isLoading, error } = useAdminData(); return <AppShell><PageHeading eyebrow="Estrutura" title="Departamentos" description="Níveis organizacionais usados para distribuir usuários e acessos." />{isLoading ? <PageLoading /> : error || !data ? <PageError message={error instanceof Error ? error.message : "Não foi possível carregar."} /> : <section className="grid grid-cols-1 gap-px overflow-hidden rounded-md border border-border bg-border md:grid-cols-2 xl:grid-cols-3">{departments.map((department) => { const count = data.users.filter((user) => user.departamento === department).length; return <article key={department} className="bg-card p-6"><Building2 className="size-5 text-primary" /><h2 className="mt-8 font-semibold">{department}</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">{descriptions[department]}</p><p className="mt-6 border-t border-border pt-4 text-sm"><strong className="text-xl">{count}</strong> <span className="text-muted-foreground">{count === 1 ? "integrante" : "integrantes"}</span></p></article>; })}</section>}</AppShell>; }
