import { useMemo, useState } from "react";
import { createFileRoute } from "@tanstack/react-router";
import { useMutation, useQueryClient } from "@tanstack/react-query";
import { useServerFn } from "@tanstack/react-start";
import { Check, Pencil, Search, UserRoundCheck, UserRoundX } from "lucide-react";
import { AppShell } from "@/components/hub/app-shell";
import { PageError, PageLoading } from "@/components/admin/page-state";
import { PageHeading } from "@/components/admin/page-heading";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { useAdminData } from "@/hooks/use-admin-data";
import { updateAdminUser } from "@/lib/admin.functions";
import { departments, type AdminUser, type Department } from "@/lib/admin-types";

export const Route = createFileRoute("/_authenticated/users")({ head: () => ({ meta: [{ title: "Usuários — Núcleo" }, { name: "description", content: "Gestão de usuários e acessos da organização." }, { property: "og:title", content: "Usuários — Núcleo" }, { property: "og:description", content: "Gestão de usuários e acessos da organização." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary" }] }), component: UsersPage });
function UsersPage() {
  const { data, isLoading, error } = useAdminData();
  const [search, setSearch] = useState(""); const [department, setDepartment] = useState("TODOS"); const [editing, setEditing] = useState<AdminUser | null>(null);
  const filtered = useMemo(() => (data?.users ?? []).filter((user) => (department === "TODOS" || user.departamento === department) && `${user.nome} ${user.email}`.toLowerCase().includes(search.toLowerCase())), [data, department, search]);
  return <AppShell><PageHeading eyebrow="Acessos" title="Usuários" description="Consulte integrantes, altere departamentos e controle quem pode acessar o sistema." /><div className="mb-5 grid gap-3 sm:grid-cols-[1fr_13rem]"><label className="relative"><span className="sr-only">Buscar usuários</span><Search className="absolute left-3 top-2.5 size-4 text-muted-foreground" /><Input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Buscar por nome ou e-mail" className="pl-9" /></label><Select value={department} onValueChange={setDepartment}><SelectTrigger aria-label="Filtrar departamento"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="TODOS">Todos os departamentos</SelectItem>{departments.map((item) => <SelectItem key={item} value={item}>{item}</SelectItem>)}</SelectContent></Select></div>{isLoading ? <PageLoading /> : error ? <PageError message={error.message} /> : <div className="overflow-x-auto rounded-md border border-border"><table className="w-full min-w-3xl text-left text-sm"><thead className="bg-secondary text-muted-foreground"><tr><th className="p-4">Usuário</th><th className="p-4">Departamento</th><th className="p-4">Status</th><th className="p-4">Cadastro</th><th className="p-4 text-right">Ação</th></tr></thead><tbody className="divide-y divide-border bg-card">{filtered.map((user) => <tr key={user.id}><td className="p-4"><p className="font-medium">{user.nome}</p><p className="text-xs text-muted-foreground">{user.email}</p></td><td className="p-4">{user.departamento}</td><td className="p-4"><span className="inline-flex items-center gap-1.5 text-xs">{user.ativo ? <UserRoundCheck className="size-4 text-primary" /> : <UserRoundX className="size-4 text-destructive" />}{user.ativo ? "Ativo" : "Inativo"}</span></td><td className="p-4 text-muted-foreground">{new Date(user.criado_em).toLocaleDateString("pt-BR")}</td><td className="p-4 text-right"><Button variant="ghost" size="icon" aria-label={`Editar ${user.nome}`} onClick={() => setEditing(user)}><Pencil /></Button></td></tr>)}{filtered.length === 0 && <tr><td colSpan={5} className="p-10 text-center text-muted-foreground">Nenhum usuário encontrado.</td></tr>}</tbody></table></div>}{editing && <EditUserDialog key={editing.id} user={editing} onClose={() => setEditing(null)} />}</AppShell>;
}
function EditUserDialog({ user, onClose }: { user: AdminUser; onClose: () => void }) {
  const queryClient = useQueryClient(); const update = useServerFn(updateAdminUser); const [name, setName] = useState(user?.nome ?? ""); const [department, setDepartment] = useState<Department>(user?.departamento ?? "VENDAS"); const [active, setActive] = useState(user?.ativo ?? true);
  const mutation = useMutation({ mutationFn: () => update({ data: { id: user.id, nome: name, departamento: department, ativo: active } }), onSuccess: async () => { await queryClient.invalidateQueries({ queryKey: ["admin-overview"] }); onClose(); } });
  return <Dialog open onOpenChange={(open) => { if (!open) onClose(); }}><DialogContent><DialogHeader><DialogTitle>Editar usuário</DialogTitle><DialogDescription>{user.email}</DialogDescription></DialogHeader><div className="grid gap-4"><Input aria-label="Nome" value={name} onChange={(event) => setName(event.target.value)} /><Select value={department} onValueChange={(value) => setDepartment(value as Department)}><SelectTrigger aria-label="Departamento"><SelectValue /></SelectTrigger><SelectContent>{departments.map((item) => <SelectItem key={item} value={item}>{item}</SelectItem>)}</SelectContent></Select><Button variant={active ? "outline" : "secondary"} onClick={() => setActive((value) => !value)}>{active ? <UserRoundCheck /> : <UserRoundX />}{active ? "Acesso ativo" : "Acesso inativo"}</Button>{mutation.error && <p role="alert" className="text-sm text-destructive">{mutation.error.message}</p>}</div><DialogFooter><Button variant="ghost" onClick={onClose}>Cancelar</Button><Button disabled={mutation.isPending || name.trim().length < 2} onClick={() => mutation.mutate()}><Check />Salvar</Button></DialogFooter></DialogContent></Dialog>;
}
